server: 
  port: 3000
  origin: 'http://localhost:4200/'
  mode: 'development'
db: 
  type: 'postgres'
  host: 'localhost'
  username: 'postgres'
  database: 'covid'
  password: 1
  synchronize: true
jwt: 
  secret: 'TopSecret51'
mail:
  service: 'gmail'
  email: 'virusmutationsai@gmail.com'
  pass: 'Virus123!'
  subject: 'VirusMutationsAI'

