version: "3.1"

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "covid"
      DB_USER: "covid"
      DB_USER_PASSWORD: "covid"
    volumes:
      - "./volumes/pg-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./volumes/pg-data:/var/lib/postgresql/data"

  frontend:
    image: docker.pkg.github.com/covidmutations/virusmutationsai/fe:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      API2_URL: "http://localhost:8000/api"

  backend2:
    image: docker.pkg.github.com/covidmutations/virusmutationsai/be2:latest
    restart: unless-stopped
    depends_on:
      - db
      - migration
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: "db"
      POSTGRES_USER: "covid"
      POSTGRES_PASSWORD: "covid"
      POSTGRES_DB: "covid"
      POSTGRES_PORT: "5432"
      SECRET_KEY: "TopSecret51"
      ENTREZ_EMAIL: "mail@example.com"
      EMAIL_FROM: "mail@example.com"
      GMAIL_CREDENTIALS_PATH: "/credentials/gmail/oauth.json"

  migration:
    image: docker.pkg.github.com/covidmutations/virusmutationsai/be2:latest
    depends_on:
      - db
    environment:
      POSTGRES_SERVER: "db"
      POSTGRES_USER: "covid"
      POSTGRES_PASSWORD: "covid"
      POSTGRES_DB: "covid"
      POSTGRES_PORT: "5432"
    command: ["python", "-m", "alembic.config", "upgrade", "head"]
